Thu Dec 05 14:58:39 GMT 2019 : Apache Derby Network Server - 10.14.2.0 - (1828579) started and ready to accept connections on port 1527
----------------------------------------------------------------
Thu Dec 05 14:58:46 GMT 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.14.2.0 - (1828579): instance a816c00e-016e-d691-f403-ffffcbf620d1 
on database directory C:\Users\p017962i\Documents\GreenLine-Passengers-Back-End-Customer\GreenLine-Passengers\jdbc\Database1 with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/C:/_NETBEANS/GlassFish%20Server%205.0/javadb/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_211-b12
user.dir=C:\_NETBEANS\GlassFish Server 5.0\javadb
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\p017962i\Documents\GreenLine-Passengers-Back-End-Customer\GreenLine-Passengers\jdbc
Database Class Loader started - derby.database.classpath=''
Thu Dec 05 14:58:47 GMT 2019 Thread[DRDAConnThread_2,5,main] (XID = 815), (SESSIONID = 0), (DATABASE = Database1), (DRDAID = {1}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 21 more
============= begin nested exception, level (1) ===========
ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Dec 05 14:58:47 GMT 2019 Thread[DRDAConnThread_2,5,main] (DATABASE = Database1), (DRDAID = {1}), Connection authentication failure occurred.  Reason: Invalid authentication..
----------------------------------------------------------------
Thu Dec 05 15:13:28 GMT 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.14.2.0 - (1828579): instance 601a400f-016e-d691-f403-ffffcbf620d1 
on database directory C:\Users\p017962i\Documents\GreenLine-Passengers-Back-End-Customer\GreenLine-Passengers\jdbc\Database05 with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/C:/_NETBEANS/GlassFish%20Server%205.0/javadb/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_211-b12
user.dir=C:\_NETBEANS\GlassFish Server 5.0\javadb
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\p017962i\Documents\GreenLine-Passengers-Back-End-Customer\GreenLine-Passengers\jdbc
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Thu Dec 05 15:13:29 GMT 2019:
Shutting down instance 601a400f-016e-d691-f403-ffffcbf620d1 on database directory C:\Users\p017962i\Documents\GreenLine-Passengers-Back-End-Customer\GreenLine-Passengers\jdbc\Database05 with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Thu Dec 05 15:13:29 GMT 2019 Thread[DRDAConnThread_2,5,main] (DATABASE = Database05), (DRDAID = {3}), Database 'Database05' shutdown.
----------------------------------------------------------------
Thu Dec 05 15:13:31 GMT 2019:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.14.2.0 - (1828579): instance 070a00b0-016e-d691-f403-ffffcbf620d1 
on database directory C:\Users\p017962i\Documents\GreenLine-Passengers-Back-End-Customer\GreenLine-Passengers\jdbc\Database05 with class loader sun.misc.Launcher$AppClassLoader@1d44bcfa 
Loaded from file:/C:/_NETBEANS/GlassFish%20Server%205.0/javadb/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_211-b12
user.dir=C:\_NETBEANS\GlassFish Server 5.0\javadb
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\p017962i\Documents\GreenLine-Passengers-Back-End-Customer\GreenLine-Passengers\jdbc
Database Class Loader started - derby.database.classpath=''
